### ISSUE TITLE
dlopen symbol not found issue with M1 wheel

### ISSUE THREAD

**Issue by sid-kap** [Quantco/tabmat#220]
I'm getting the following error when trying to import tabmat using the `tabmat-3.1.3-cp38-cp38-macosx_11_0_arm64.whl` wheel:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sidharthkapur/test-workspace/tabmat-test/lib/python3.8/site-packages/tabmat/__init__.py", line 1, in <module>
    from .categorical_matrix import CategoricalMatrix
  File "/Users/sidharthkapur/test-workspace/tabmat-test/lib/python3.8/site-packages/tabmat/categorical_matrix.py", line 182, in <module>
    from .sparse_matrix import SparseMatrix
  File "/Users/sidharthkapur/test-workspace/tabmat-test/lib/python3.8/site-packages/tabmat/sparse_matrix.py", line 6, in <module>
    from .ext.sparse import (
ImportError: dlopen(/Users/sidharthkapur/test-workspace/tabmat-test/lib/python3.8/site-packages/tabmat/ext/sparse.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_je_aligned_alloc'
```

Steps to reproduce:
```sh
python3.8 -m venv ./tabmat-test
source ./tabmat-test/bin/activate
pip install tabmat==3.1.3
# Collecting tabmat
#   Using cached tabmat-3.1.3-cp38-cp38-macosx_11_0_arm64.whl (590 kB)
# Collecting pandas
#   Downloading pandas-1.5.3-cp38-cp38-macosx_11_0_arm64.whl (10.8 MB)
#      |████████████████████████████████| 10.8 MB 15.3 MB/s
# Collecting numpy
#   Using cached numpy-1.24.1-cp38-cp38-macosx_11_0_arm64.whl (13.8 MB)
# Collecting scipy
#   Using cached scipy-1.10.0-cp38-cp38-macosx_12_0_arm64.whl (28.8 MB)
# Collecting python-dateutil>=2.8.1
#   Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
# Collecting pytz>=2020.1
#   Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
#      |████████████████████████████████| 499 kB 82.4 MB/s
# Collecting six>=1.5
#   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
# Installing collected packages: six, pytz, python-dateutil, numpy, scipy, pandas, tabmat
# Successfully installed numpy-1.24.1 pandas-1.5.3 python-dateutil-2.8.2 pytz-2022.7.1 scipy-1.10.0 six-1.16.0 tabmat-3.1.3
python -c 'import tabmat'
```

**Comment by david-cortes** [comment]
@xhochy I am seeing a similar error with the prebuilt wheel for `tabmat==3.1.4` from PyPI, but the problematic symbol now is `_localaligned_alloc`. It imports just fine if I compile it from source after also installing `jemalloc` from source with the same options as in your CI jobs.

**Comment by xhochy** [comment]
I'm getting the following error locally:

```
Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tabmat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uwe/tmp/tabmat/lib/python3.11/site-packages/tabmat/__init__.py", line 1, in <module>
    from .categorical_matrix import CategoricalMatrix
  File "/Users/uwe/tmp/tabmat/lib/python3.11/site-packages/tabmat/categorical_matrix.py", line 170, in <module>
    from .ext.categorical import (
ImportError: dlopen(/Users/uwe/tmp/tabmat/lib/python3.11/site-packages/tabmat/ext/categorical.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '___kmpc_barrier'
```

**Comment by xhochy** [comment]
Using `-lomp` brings us back to @david-cortes original error:

```
>>> import tabmat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uwe/micromamba/envs/tabmat/lib/python3.11/site-packages/tabmat/__init__.py", line 1, in <module>
    from .categorical_matrix import CategoricalMatrix
  File "/Users/uwe/micromamba/envs/tabmat/lib/python3.11/site-packages/tabmat/categorical_matrix.py", line 182, in <module>
    from .sparse_matrix import SparseMatrix
  File "/Users/uwe/micromamba/envs/tabmat/lib/python3.11/site-packages/tabmat/sparse_matrix.py", line 6, in <module>
    from .ext.sparse import (
ImportError: dlopen(/Users/uwe/micromamba/envs/tabmat/lib/python3.11/site-packages/tabmat/ext/sparse.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_localaligned_alloc'
```
